services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5000:80
    depends_on:
      - ollama
    networks:
      - rede_interna
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 8501:8501
    depends_on:
      - backend
    networks:
      - rede_interna
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - rede_interna
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  ollama:

networks:
  rede_interna:
    driver: bridge